// Shared suggestion lists for ComboboxInput across the admin panel

export const ZONAS_MEXICO = [
  // Área Metropolitana de Monterrey
  "San Pedro Garza García, NL",
  "Monterrey, NL",
  "San Nicolás de los Garza, NL",
  "Guadalupe, NL",
  "Apodaca, NL",
  "General Escobedo, NL",
  "Santa Catarina, NL",
  "Juárez, NL",
  "García, NL",
  "Cadereyta Jiménez, NL",
  // Resto de NL
  "Linares, NL",
  "Montemorelos, NL",
  "Santiago, NL",
  "Allende, NL",
  "Sabinas Hidalgo, NL",
  // Otras ciudades principales de México
  "CDMX / Ciudad de México",
  "Guadalajara, JAL",
  "Zapopan, JAL",
  "Tlaquepaque, JAL",
  "Puebla, PUE",
  "Querétaro, QRO",
  "León, GTO",
  "Silao, GTO",
  "Irapuato, GTO",
  "Celaya, GTO",
  "Tijuana, BC",
  "Ensenada, BC",
  "Mexicali, BC",
  "Mérida, YUC",
  "Cancún, QROO",
  "Playa del Carmen, QROO",
  "Tulum, QROO",
  "Hermosillo, SON",
  "Chihuahua, CHIH",
  "Ciudad Juárez, CHIH",
  "San Luis Potosí, SLP",
  "Aguascalientes, AGS",
  "Saltillo, COAH",
  "Torreón, COAH",
  "Monclova, COAH",
  "Veracruz, VER",
  "Xalapa, VER",
  "Morelia, MICH",
  "Toluca, MEX",
  "Ecatepec, MEX",
  "Naucalpan, MEX",
  "Tlalnepantla, MEX",
  "Culiacán, SIN",
  "Mazatlán, SIN",
  "Durango, DGO",
  "Oaxaca, OAX",
  "Tuxtla Gutiérrez, CHIS",
  "Villahermosa, TAB",
  "Tampico, TAMPS",
  "Ciudad Victoria, TAMPS",
  "Reynosa, TAMPS",
  "Matamoros, TAMPS",
  "Nuevo Laredo, TAMPS",
  "Colima, COL",
  "Tepic, NAY",
  "Zacatecas, ZAC",
  "Campeche, CAMP",
  "Chetumal, QROO",
  "La Paz, BCS",
  "Los Cabos, BCS",
];

export const GIROS_NEGOCIO = [
  "Restaurante",
  "Cafetería",
  "Taquería / Comida rápida",
  "Panadería / Repostería",
  "Pastelería",
  "Heladería",
  "Bar / Cantina",
  "Salón de Belleza",
  "Salón de Uñas",
  "Barbería",
  "Spa / Centro de bienestar",
  "Gimnasio / Fitness",
  "Yoga / Pilates",
  "Estética canina",
  "Consultorio Médico",
  "Consultorio Dental",
  "Consultorio de Nutrición",
  "Psicología / Terapia",
  "Veterinaria",
  "Farmacia",
  "Óptica",
  "Tienda de Ropa",
  "Boutique",
  "Zapatería",
  "Tienda en línea / E-commerce",
  "Agencia de Marketing Digital",
  "Agencia de Publicidad",
  "Diseño Gráfico",
  "Fotografía",
  "Videografía / Video producción",
  "Despacho Contable",
  "Despacho Legal / Abogado",
  "Inmobiliaria",
  "Constructora",
  "Arquitectura / Diseño de interiores",
  "Taller Mecánico",
  "Refaccionaria",
  "Escuela / Academia privada",
  "Centro de idiomas",
  "Guardería / Kinder",
  "Floristería",
  "Joyería",
  "Mueblería",
  "Papelería / Imprenta",
  "Lavandería",
  "Mudanzas / Logística",
  "Agencia de viajes",
  "Hotel / Hostal",
  "Evento / Banquetes",
  "Seguridad privada",
  "Tecnología / Software",
  "Consultoría empresarial",
  "Reclutamiento / RRHH",
  "Seguros",
  "Otro",
];

export const CONCEPTOS_PAGO = [
  "Mensualidad de servicios digitales",
  "Gestión de redes sociales",
  "Gestión de Google Ads",
  "Gestión de Meta Ads",
  "Diseño y desarrollo de sitio web",
  "Mantenimiento mensual de sitio web",
  "Diseño gráfico mensual",
  "Producción de contenido",
  "Fotografía de producto",
  "Campaña publicitaria",
  "Consultoría de marketing",
  "Estrategia digital",
  "SEO mensual",
  "Email marketing mensual",
  "Onboarding / Inicio de servicios",
  "Pago inicial / Anticipo",
  "Segunda mensualidad",
  "Liquidación de proyecto",
  "Reporte mensual de resultados",
  "Servicio adicional",
];
